# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Rose', 'Rose')], max_length=15)),
                ('quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('kasaNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('RunCommand', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='KasaFabrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricQuanity', models.FloatField()),
                ('Kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasni3.Kasa')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasni3.Fabric')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('modelNumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='kasa',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasni3.Model'),
        ),
    ]
