# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasni3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kasafabrics',
            old_name='Kasa',
            new_name='kasa',
        ),
    ]
